name: trailshare_flutter
description: "TrailShare - GPS Tracking per escursioni e trail running"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  http: ^1.6.0

  # Firebase
  firebase_core: ^3.9.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.4.0

  # Mappe
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  
  # Location
  geolocator: ^14.0.2
  permission_handler: ^11.3.1

  # State management
  provider: ^6.1.2

  # Charts
  fl_chart: ^1.1.1

  # File sharing
  path_provider: ^2.1.5

  # Social Auth
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4
  crypto: ^3.0.6
  xml: ^6.6.1
  file_picker: ^10.3.8
  share_plus: ^12.0.1
  flutter_foreground_task: ^9.2.0
  battery_plus: ^7.0.0
  url_launcher: ^6.3.2
  package_info_plus: ^9.0.0

  #supporto BLE
  flutter_blue_plus: ^1.16.0
  
  # Camera & Photos
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

